/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreationDeGroupeDTO
 */
export interface CreationDeGroupeDTO {
    /**
     * 
     * @type {string}
     * @memberof CreationDeGroupeDTO
     */
    chefID?: string;
    /**
     * 
     * @type {string}
     * @memberof CreationDeGroupeDTO
     */
    nomGroup?: string;
}

/**
 * Check if a given object implements the CreationDeGroupeDTO interface.
 */
export function instanceOfCreationDeGroupeDTO(value: object): value is CreationDeGroupeDTO {
    return true;
}

export function CreationDeGroupeDTOFromJSON(json: any): CreationDeGroupeDTO {
    return CreationDeGroupeDTOFromJSONTyped(json, false);
}

export function CreationDeGroupeDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreationDeGroupeDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'chefID': json['chefID'] == null ? undefined : json['chefID'],
        'nomGroup': json['nomGroup'] == null ? undefined : json['nomGroup'],
    };
}

export function CreationDeGroupeDTOToJSON(json: any): CreationDeGroupeDTO {
    return CreationDeGroupeDTOToJSONTyped(json, false);
}

export function CreationDeGroupeDTOToJSONTyped(value?: CreationDeGroupeDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'chefID': value['chefID'],
        'nomGroup': value['nomGroup'],
    };
}

