/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RetourInvitationDTO
 */
export interface RetourInvitationDTO {
    /**
     * 
     * @type {string}
     * @memberof RetourInvitationDTO
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof RetourInvitationDTO
     */
    etudiantNomUtilisateur?: string;
    /**
     * 
     * @type {string}
     * @memberof RetourInvitationDTO
     */
    message?: string;
    /**
     * 
     * @type {RetourInvitationDTOTypeEnum}
     * @memberof RetourInvitationDTO
     */
    type?: RetourInvitationDTOTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof RetourInvitationDTO
     */
    titre?: string;
    /**
     * 
     * @type {string}
     * @memberof RetourInvitationDTO
     */
    destination?: string;
    /**
     * 
     * @type {string}
     * @memberof RetourInvitationDTO
     */
    envoyeurId?: string;
    /**
     * 
     * @type {RetourInvitationDTOTypeInvitationEnum}
     * @memberof RetourInvitationDTO
     */
    typeInvitation?: RetourInvitationDTOTypeInvitationEnum;
}


/**
 * @export
 */
export const RetourInvitationDTOTypeEnum = {
    NouvelleGroupeInvitation: 'NOUVELLE_GROUPE_INVITATION',
    NouvelleConversationInvitation: 'NOUVELLE_CONVERSATION_INVITATION',
    AlerteSysteme: 'ALERTE_SYSTEME'
} as const;
export type RetourInvitationDTOTypeEnum = typeof RetourInvitationDTOTypeEnum[keyof typeof RetourInvitationDTOTypeEnum];

/**
 * @export
 */
export const RetourInvitationDTOTypeInvitationEnum = {
    Groupe: 'GROUPE',
    Conversation: 'CONVERSATION'
} as const;
export type RetourInvitationDTOTypeInvitationEnum = typeof RetourInvitationDTOTypeInvitationEnum[keyof typeof RetourInvitationDTOTypeInvitationEnum];


/**
 * Check if a given object implements the RetourInvitationDTO interface.
 */
export function instanceOfRetourInvitationDTO(value: object): value is RetourInvitationDTO {
    return true;
}

export function RetourInvitationDTOFromJSON(json: any): RetourInvitationDTO {
    return RetourInvitationDTOFromJSONTyped(json, false);
}

export function RetourInvitationDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): RetourInvitationDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'etudiantNomUtilisateur': json['etudiantNomUtilisateur'] == null ? undefined : json['etudiantNomUtilisateur'],
        'message': json['message'] == null ? undefined : json['message'],
        'type': json['type'] == null ? undefined : json['type'],
        'titre': json['titre'] == null ? undefined : json['titre'],
        'destination': json['destination'] == null ? undefined : json['destination'],
        'envoyeurId': json['envoyeurId'] == null ? undefined : json['envoyeurId'],
        'typeInvitation': json['typeInvitation'] == null ? undefined : json['typeInvitation'],
    };
}

export function RetourInvitationDTOToJSON(json: any): RetourInvitationDTO {
    return RetourInvitationDTOToJSONTyped(json, false);
}

export function RetourInvitationDTOToJSONTyped(value?: RetourInvitationDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'etudiantNomUtilisateur': value['etudiantNomUtilisateur'],
        'message': value['message'],
        'type': value['type'],
        'titre': value['titre'],
        'destination': value['destination'],
        'envoyeurId': value['envoyeurId'],
        'typeInvitation': value['typeInvitation'],
    };
}

