/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RetourHoraireDTO } from './RetourHoraireDTO';
import {
    RetourHoraireDTOFromJSON,
    RetourHoraireDTOFromJSONTyped,
    RetourHoraireDTOToJSON,
    RetourHoraireDTOToJSONTyped,
} from './RetourHoraireDTO';

/**
 * 
 * @export
 * @interface RetourEtudiantDTO
 */
export interface RetourEtudiantDTO {
    /**
     * 
     * @type {string}
     * @memberof RetourEtudiantDTO
     */
    etudiantId?: string;
    /**
     * 
     * @type {string}
     * @memberof RetourEtudiantDTO
     */
    nomUtilisateur?: string;
    /**
     * 
     * @type {string}
     * @memberof RetourEtudiantDTO
     */
    prenom?: string;
    /**
     * 
     * @type {string}
     * @memberof RetourEtudiantDTO
     */
    nom?: string;
    /**
     * 
     * @type {string}
     * @memberof RetourEtudiantDTO
     */
    email?: string;
    /**
     * 
     * @type {RetourHoraireDTO}
     * @memberof RetourEtudiantDTO
     */
    retourHoraireDTO?: RetourHoraireDTO;
}

/**
 * Check if a given object implements the RetourEtudiantDTO interface.
 */
export function instanceOfRetourEtudiantDTO(value: object): value is RetourEtudiantDTO {
    return true;
}

export function RetourEtudiantDTOFromJSON(json: any): RetourEtudiantDTO {
    return RetourEtudiantDTOFromJSONTyped(json, false);
}

export function RetourEtudiantDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): RetourEtudiantDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'etudiantId': json['etudiantId'] == null ? undefined : json['etudiantId'],
        'nomUtilisateur': json['nomUtilisateur'] == null ? undefined : json['nomUtilisateur'],
        'prenom': json['prenom'] == null ? undefined : json['prenom'],
        'nom': json['nom'] == null ? undefined : json['nom'],
        'email': json['email'] == null ? undefined : json['email'],
        'retourHoraireDTO': json['retourHoraireDTO'] == null ? undefined : RetourHoraireDTOFromJSON(json['retourHoraireDTO']),
    };
}

export function RetourEtudiantDTOToJSON(json: any): RetourEtudiantDTO {
    return RetourEtudiantDTOToJSONTyped(json, false);
}

export function RetourEtudiantDTOToJSONTyped(value?: RetourEtudiantDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'etudiantId': value['etudiantId'],
        'nomUtilisateur': value['nomUtilisateur'],
        'prenom': value['prenom'],
        'nom': value['nom'],
        'email': value['email'],
        'retourHoraireDTO': RetourHoraireDTOToJSON(value['retourHoraireDTO']),
    };
}

