/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Activite } from './Activite';
import {
    ActiviteFromJSON,
    ActiviteFromJSONTyped,
    ActiviteToJSON,
    ActiviteToJSONTyped,
} from './Activite';

/**
 * 
 * @export
 * @interface AjouterActiviteDTOEtudiant
 */
export interface AjouterActiviteDTOEtudiant {
    /**
     * 
     * @type {Activite}
     * @memberof AjouterActiviteDTOEtudiant
     */
    activite?: Activite;
    /**
     * 
     * @type {string}
     * @memberof AjouterActiviteDTOEtudiant
     */
    etudiantId?: string;
}

/**
 * Check if a given object implements the AjouterActiviteDTOEtudiant interface.
 */
export function instanceOfAjouterActiviteDTOEtudiant(value: object): value is AjouterActiviteDTOEtudiant {
    return true;
}

export function AjouterActiviteDTOEtudiantFromJSON(json: any): AjouterActiviteDTOEtudiant {
    return AjouterActiviteDTOEtudiantFromJSONTyped(json, false);
}

export function AjouterActiviteDTOEtudiantFromJSONTyped(json: any, ignoreDiscriminator: boolean): AjouterActiviteDTOEtudiant {
    if (json == null) {
        return json;
    }
    return {
        
        'activite': json['activite'] == null ? undefined : ActiviteFromJSON(json['activite']),
        'etudiantId': json['etudiantId'] == null ? undefined : json['etudiantId'],
    };
}

export function AjouterActiviteDTOEtudiantToJSON(json: any): AjouterActiviteDTOEtudiant {
    return AjouterActiviteDTOEtudiantToJSONTyped(json, false);
}

export function AjouterActiviteDTOEtudiantToJSONTyped(value?: AjouterActiviteDTOEtudiant | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'activite': ActiviteToJSON(value['activite']),
        'etudiantId': value['etudiantId'],
    };
}

