/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreationConversationDTO
 */
export interface CreationConversationDTO {
    /**
     * 
     * @type {string}
     * @memberof CreationConversationDTO
     */
    chefId?: string;
    /**
     * 
     * @type {string}
     * @memberof CreationConversationDTO
     */
    nomConversation?: string;
}

/**
 * Check if a given object implements the CreationConversationDTO interface.
 */
export function instanceOfCreationConversationDTO(value: object): value is CreationConversationDTO {
    return true;
}

export function CreationConversationDTOFromJSON(json: any): CreationConversationDTO {
    return CreationConversationDTOFromJSONTyped(json, false);
}

export function CreationConversationDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreationConversationDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'chefId': json['chefId'] == null ? undefined : json['chefId'],
        'nomConversation': json['nomConversation'] == null ? undefined : json['nomConversation'],
    };
}

export function CreationConversationDTOToJSON(json: any): CreationConversationDTO {
    return CreationConversationDTOToJSONTyped(json, false);
}

export function CreationConversationDTOToJSONTyped(value?: CreationConversationDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'chefId': value['chefId'],
        'nomConversation': value['nomConversation'],
    };
}

