/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreationEtudiantDTO
 */
export interface CreationEtudiantDTO {
    /**
     * 
     * @type {string}
     * @memberof CreationEtudiantDTO
     */
    prenom: string;
    /**
     * 
     * @type {string}
     * @memberof CreationEtudiantDTO
     */
    nom: string;
    /**
     * 
     * @type {string}
     * @memberof CreationEtudiantDTO
     */
    nomUtilisateur: string;
    /**
     * 
     * @type {string}
     * @memberof CreationEtudiantDTO
     */
    ecole: string;
    /**
     * 
     * @type {string}
     * @memberof CreationEtudiantDTO
     */
    motDePasse: string;
    /**
     * 
     * @type {string}
     * @memberof CreationEtudiantDTO
     */
    courriel: string;
}

/**
 * Check if a given object implements the CreationEtudiantDTO interface.
 */
export function instanceOfCreationEtudiantDTO(value: object): value is CreationEtudiantDTO {
    if (!('prenom' in value) || value['prenom'] === undefined) return false;
    if (!('nom' in value) || value['nom'] === undefined) return false;
    if (!('nomUtilisateur' in value) || value['nomUtilisateur'] === undefined) return false;
    if (!('ecole' in value) || value['ecole'] === undefined) return false;
    if (!('motDePasse' in value) || value['motDePasse'] === undefined) return false;
    if (!('courriel' in value) || value['courriel'] === undefined) return false;
    return true;
}

export function CreationEtudiantDTOFromJSON(json: any): CreationEtudiantDTO {
    return CreationEtudiantDTOFromJSONTyped(json, false);
}

export function CreationEtudiantDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreationEtudiantDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'prenom': json['prenom'],
        'nom': json['nom'],
        'nomUtilisateur': json['nomUtilisateur'],
        'ecole': json['ecole'],
        'motDePasse': json['motDePasse'],
        'courriel': json['courriel'],
    };
}

export function CreationEtudiantDTOToJSON(json: any): CreationEtudiantDTO {
    return CreationEtudiantDTOToJSONTyped(json, false);
}

export function CreationEtudiantDTOToJSONTyped(value?: CreationEtudiantDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'prenom': value['prenom'],
        'nom': value['nom'],
        'nomUtilisateur': value['nomUtilisateur'],
        'ecole': value['ecole'],
        'motDePasse': value['motDePasse'],
        'courriel': value['courriel'],
    };
}

