/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Horaire } from './Horaire';
import {
    HoraireFromJSON,
    HoraireFromJSONTyped,
    HoraireToJSON,
    HoraireToJSONTyped,
} from './Horaire';
import type { Notification } from './Notification';
import {
    NotificationFromJSON,
    NotificationFromJSONTyped,
    NotificationToJSON,
    NotificationToJSONTyped,
} from './Notification';

/**
 * 
 * @export
 * @interface Etudiant
 */
export interface Etudiant {
    /**
     * 
     * @type {string}
     * @memberof Etudiant
     */
    id?: string;
    /**
     * 
     * @type {Date}
     * @memberof Etudiant
     */
    dernierDate?: Date;
    /**
     * 
     * @type {string}
     * @memberof Etudiant
     */
    courriel?: string;
    /**
     * 
     * @type {string}
     * @memberof Etudiant
     */
    nomUtilisateur?: string;
    /**
     * 
     * @type {string}
     * @memberof Etudiant
     */
    nom?: string;
    /**
     * 
     * @type {string}
     * @memberof Etudiant
     */
    prenom?: string;
    /**
     * 
     * @type {string}
     * @memberof Etudiant
     */
    ecole?: string;
    /**
     * 
     * @type {Horaire}
     * @memberof Etudiant
     */
    horaire?: Horaire;
    /**
     * 
     * @type {Array<Notification>}
     * @memberof Etudiant
     */
    notifications?: Array<Notification>;
}

/**
 * Check if a given object implements the Etudiant interface.
 */
export function instanceOfEtudiant(value: object): value is Etudiant {
    return true;
}

export function EtudiantFromJSON(json: any): Etudiant {
    return EtudiantFromJSONTyped(json, false);
}

export function EtudiantFromJSONTyped(json: any, ignoreDiscriminator: boolean): Etudiant {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'dernierDate': json['dernierDate'] == null ? undefined : (new Date(json['dernierDate'])),
        'courriel': json['courriel'] == null ? undefined : json['courriel'],
        'nomUtilisateur': json['nomUtilisateur'] == null ? undefined : json['nomUtilisateur'],
        'nom': json['nom'] == null ? undefined : json['nom'],
        'prenom': json['prenom'] == null ? undefined : json['prenom'],
        'ecole': json['ecole'] == null ? undefined : json['ecole'],
        'horaire': json['horaire'] == null ? undefined : HoraireFromJSON(json['horaire']),
        'notifications': json['notifications'] == null ? undefined : ((json['notifications'] as Array<any>).map(NotificationFromJSON)),
    };
}

export function EtudiantToJSON(json: any): Etudiant {
    return EtudiantToJSONTyped(json, false);
}

export function EtudiantToJSONTyped(value?: Etudiant | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'dernierDate': value['dernierDate'] == null ? value['dernierDate'] : value['dernierDate'].toISOString().substring(0,10),
        'courriel': value['courriel'],
        'nomUtilisateur': value['nomUtilisateur'],
        'nom': value['nom'],
        'prenom': value['prenom'],
        'ecole': value['ecole'],
        'horaire': HoraireToJSON(value['horaire']),
        'notifications': value['notifications'] == null ? undefined : ((value['notifications'] as Array<any>).map(NotificationToJSON)),
    };
}

