/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Message
 */
export interface Message {
    /**
     * 
     * @type {string}
     * @memberof Message
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof Message
     */
    envoyeurId?: string;
    /**
     * 
     * @type {string}
     * @memberof Message
     */
    contenu?: string;
    /**
     * 
     * @type {Date}
     * @memberof Message
     */
    tempsEnvoi?: Date;
}

/**
 * Check if a given object implements the Message interface.
 */
export function instanceOfMessage(value: object): value is Message {
    return true;
}

export function MessageFromJSON(json: any): Message {
    return MessageFromJSONTyped(json, false);
}

export function MessageFromJSONTyped(json: any, ignoreDiscriminator: boolean): Message {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'envoyeurId': json['envoyeurId'] == null ? undefined : json['envoyeurId'],
        'contenu': json['contenu'] == null ? undefined : json['contenu'],
        'tempsEnvoi': json['tempsEnvoi'] == null ? undefined : (new Date(json['tempsEnvoi'])),
    };
}

export function MessageToJSON(json: any): Message {
    return MessageToJSONTyped(json, false);
}

export function MessageToJSONTyped(value?: Message | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'envoyeurId': value['envoyeurId'],
        'contenu': value['contenu'],
        'tempsEnvoi': value['tempsEnvoi'] == null ? value['tempsEnvoi'] : value['tempsEnvoi'].toISOString(),
    };
}

