/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MiseAJourEtudiantProfil
 */
export interface MiseAJourEtudiantProfil {
    /**
     * 
     * @type {string}
     * @memberof MiseAJourEtudiantProfil
     */
    etudiantID?: string;
    /**
     * 
     * @type {string}
     * @memberof MiseAJourEtudiantProfil
     */
    nomUtilisateur?: string;
    /**
     * 
     * @type {string}
     * @memberof MiseAJourEtudiantProfil
     */
    nom?: string;
    /**
     * 
     * @type {string}
     * @memberof MiseAJourEtudiantProfil
     */
    prenom?: string;
    /**
     * 
     * @type {string}
     * @memberof MiseAJourEtudiantProfil
     */
    ecole?: string;
}

/**
 * Check if a given object implements the MiseAJourEtudiantProfil interface.
 */
export function instanceOfMiseAJourEtudiantProfil(value: object): value is MiseAJourEtudiantProfil {
    return true;
}

export function MiseAJourEtudiantProfilFromJSON(json: any): MiseAJourEtudiantProfil {
    return MiseAJourEtudiantProfilFromJSONTyped(json, false);
}

export function MiseAJourEtudiantProfilFromJSONTyped(json: any, ignoreDiscriminator: boolean): MiseAJourEtudiantProfil {
    if (json == null) {
        return json;
    }
    return {
        
        'etudiantID': json['etudiantID'] == null ? undefined : json['etudiantID'],
        'nomUtilisateur': json['nomUtilisateur'] == null ? undefined : json['nomUtilisateur'],
        'nom': json['nom'] == null ? undefined : json['nom'],
        'prenom': json['prenom'] == null ? undefined : json['prenom'],
        'ecole': json['ecole'] == null ? undefined : json['ecole'],
    };
}

export function MiseAJourEtudiantProfilToJSON(json: any): MiseAJourEtudiantProfil {
    return MiseAJourEtudiantProfilToJSONTyped(json, false);
}

export function MiseAJourEtudiantProfilToJSONTyped(value?: MiseAJourEtudiantProfil | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'etudiantID': value['etudiantID'],
        'nomUtilisateur': value['nomUtilisateur'],
        'nom': value['nom'],
        'prenom': value['prenom'],
        'ecole': value['ecole'],
    };
}

