/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MiseAJourEtudiantMotDePasse
 */
export interface MiseAJourEtudiantMotDePasse {
    /**
     * 
     * @type {string}
     * @memberof MiseAJourEtudiantMotDePasse
     */
    etudiantID?: string;
    /**
     * 
     * @type {string}
     * @memberof MiseAJourEtudiantMotDePasse
     */
    vieuxMotDePasse?: string;
    /**
     * 
     * @type {string}
     * @memberof MiseAJourEtudiantMotDePasse
     */
    nouveauMotDePasse?: string;
}

/**
 * Check if a given object implements the MiseAJourEtudiantMotDePasse interface.
 */
export function instanceOfMiseAJourEtudiantMotDePasse(value: object): value is MiseAJourEtudiantMotDePasse {
    return true;
}

export function MiseAJourEtudiantMotDePasseFromJSON(json: any): MiseAJourEtudiantMotDePasse {
    return MiseAJourEtudiantMotDePasseFromJSONTyped(json, false);
}

export function MiseAJourEtudiantMotDePasseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MiseAJourEtudiantMotDePasse {
    if (json == null) {
        return json;
    }
    return {
        
        'etudiantID': json['etudiantID'] == null ? undefined : json['etudiantID'],
        'vieuxMotDePasse': json['vieuxMotDePasse'] == null ? undefined : json['vieuxMotDePasse'],
        'nouveauMotDePasse': json['nouveauMotDePasse'] == null ? undefined : json['nouveauMotDePasse'],
    };
}

export function MiseAJourEtudiantMotDePasseToJSON(json: any): MiseAJourEtudiantMotDePasse {
    return MiseAJourEtudiantMotDePasseToJSONTyped(json, false);
}

export function MiseAJourEtudiantMotDePasseToJSONTyped(value?: MiseAJourEtudiantMotDePasse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'etudiantID': value['etudiantID'],
        'vieuxMotDePasse': value['vieuxMotDePasse'],
        'nouveauMotDePasse': value['nouveauMotDePasse'],
    };
}

