/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Notification
 */
export interface Notification {
    /**
     * 
     * @type {string}
     * @memberof Notification
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof Notification
     */
    message?: string;
    /**
     * 
     * @type {NotificationTypeEnum}
     * @memberof Notification
     */
    type?: NotificationTypeEnum;
    /**
     * 
     * @type {Date}
     * @memberof Notification
     */
    tempsCreation?: Date;
    /**
     * 
     * @type {string}
     * @memberof Notification
     */
    titre?: string;
    /**
     * 
     * @type {boolean}
     * @memberof Notification
     */
    estVu?: boolean;
}


/**
 * @export
 */
export const NotificationTypeEnum = {
    NouvelleGroupeInvitation: 'NOUVELLE_GROUPE_INVITATION',
    NouvelleConversationInvitation: 'NOUVELLE_CONVERSATION_INVITATION',
    AlerteSysteme: 'ALERTE_SYSTEME'
} as const;
export type NotificationTypeEnum = typeof NotificationTypeEnum[keyof typeof NotificationTypeEnum];


/**
 * Check if a given object implements the Notification interface.
 */
export function instanceOfNotification(value: object): value is Notification {
    return true;
}

export function NotificationFromJSON(json: any): Notification {
    return NotificationFromJSONTyped(json, false);
}

export function NotificationFromJSONTyped(json: any, ignoreDiscriminator: boolean): Notification {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'message': json['message'] == null ? undefined : json['message'],
        'type': json['type'] == null ? undefined : json['type'],
        'tempsCreation': json['tempsCreation'] == null ? undefined : (new Date(json['tempsCreation'])),
        'titre': json['titre'] == null ? undefined : json['titre'],
        'estVu': json['estVu'] == null ? undefined : json['estVu'],
    };
}

export function NotificationToJSON(json: any): Notification {
    return NotificationToJSONTyped(json, false);
}

export function NotificationToJSONTyped(value?: Notification | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'message': value['message'],
        'type': value['type'],
        'tempsCreation': value['tempsCreation'] == null ? value['tempsCreation'] : value['tempsCreation'].toISOString(),
        'titre': value['titre'],
        'estVu': value['estVu'],
    };
}

