/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RequeteActiviteGroupeDTO
 */
export interface RequeteActiviteGroupeDTO {
    /**
     * 
     * @type {string}
     * @memberof RequeteActiviteGroupeDTO
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof RequeteActiviteGroupeDTO
     */
    titre?: string;
    /**
     * 
     * @type {Date}
     * @memberof RequeteActiviteGroupeDTO
     */
    tempsDebut?: Date;
    /**
     * 
     * @type {Date}
     * @memberof RequeteActiviteGroupeDTO
     */
    tempsFin?: Date;
    /**
     * 
     * @type {string}
     * @memberof RequeteActiviteGroupeDTO
     */
    horaireId?: string;
    /**
     * 
     * @type {number}
     * @memberof RequeteActiviteGroupeDTO
     */
    dureeEnMinute?: number;
}

/**
 * Check if a given object implements the RequeteActiviteGroupeDTO interface.
 */
export function instanceOfRequeteActiviteGroupeDTO(value: object): value is RequeteActiviteGroupeDTO {
    return true;
}

export function RequeteActiviteGroupeDTOFromJSON(json: any): RequeteActiviteGroupeDTO {
    return RequeteActiviteGroupeDTOFromJSONTyped(json, false);
}

export function RequeteActiviteGroupeDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): RequeteActiviteGroupeDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'description': json['description'] == null ? undefined : json['description'],
        'titre': json['titre'] == null ? undefined : json['titre'],
        'tempsDebut': json['tempsDebut'] == null ? undefined : (new Date(json['tempsDebut'])),
        'tempsFin': json['tempsFin'] == null ? undefined : (new Date(json['tempsFin'])),
        'horaireId': json['horaireId'] == null ? undefined : json['horaireId'],
        'dureeEnMinute': json['dureeEnMinute'] == null ? undefined : json['dureeEnMinute'],
    };
}

export function RequeteActiviteGroupeDTOToJSON(json: any): RequeteActiviteGroupeDTO {
    return RequeteActiviteGroupeDTOToJSONTyped(json, false);
}

export function RequeteActiviteGroupeDTOToJSONTyped(value?: RequeteActiviteGroupeDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'description': value['description'],
        'titre': value['titre'],
        'tempsDebut': value['tempsDebut'] == null ? value['tempsDebut'] : value['tempsDebut'].toISOString(),
        'tempsFin': value['tempsFin'] == null ? value['tempsFin'] : value['tempsFin'].toISOString(),
        'horaireId': value['horaireId'],
        'dureeEnMinute': value['dureeEnMinute'],
    };
}

