/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RetourMessageDTO } from './RetourMessageDTO';
import {
    RetourMessageDTOFromJSON,
    RetourMessageDTOFromJSONTyped,
    RetourMessageDTOToJSON,
    RetourMessageDTOToJSONTyped,
} from './RetourMessageDTO';

/**
 * 
 * @export
 * @interface RetourConversationDTO
 */
export interface RetourConversationDTO {
    /**
     * 
     * @type {string}
     * @memberof RetourConversationDTO
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof RetourConversationDTO
     */
    chefId?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof RetourConversationDTO
     */
    participantsIds?: Array<string>;
    /**
     * 
     * @type {boolean}
     * @memberof RetourConversationDTO
     */
    estConversationGroupe?: boolean;
    /**
     * 
     * @type {Array<RetourMessageDTO>}
     * @memberof RetourConversationDTO
     */
    messages?: Array<RetourMessageDTO>;
    /**
     * 
     * @type {string}
     * @memberof RetourConversationDTO
     */
    nom?: string;
}

/**
 * Check if a given object implements the RetourConversationDTO interface.
 */
export function instanceOfRetourConversationDTO(value: object): value is RetourConversationDTO {
    return true;
}

export function RetourConversationDTOFromJSON(json: any): RetourConversationDTO {
    return RetourConversationDTOFromJSONTyped(json, false);
}

export function RetourConversationDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): RetourConversationDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'chefId': json['chefId'] == null ? undefined : json['chefId'],
        'participantsIds': json['participantsIds'] == null ? undefined : json['participantsIds'],
        'estConversationGroupe': json['estConversationGroupe'] == null ? undefined : json['estConversationGroupe'],
        'messages': json['messages'] == null ? undefined : ((json['messages'] as Array<any>).map(RetourMessageDTOFromJSON)),
        'nom': json['nom'] == null ? undefined : json['nom'],
    };
}

export function RetourConversationDTOToJSON(json: any): RetourConversationDTO {
    return RetourConversationDTOToJSONTyped(json, false);
}

export function RetourConversationDTOToJSONTyped(value?: RetourConversationDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'chefId': value['chefId'],
        'participantsIds': value['participantsIds'],
        'estConversationGroupe': value['estConversationGroupe'],
        'messages': value['messages'] == null ? undefined : ((value['messages'] as Array<any>).map(RetourMessageDTOToJSON)),
        'nom': value['nom'],
    };
}

