/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RetourMessageDTO
 */
export interface RetourMessageDTO {
    /**
     * 
     * @type {string}
     * @memberof RetourMessageDTO
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof RetourMessageDTO
     */
    envoyeurId?: string;
    /**
     * 
     * @type {string}
     * @memberof RetourMessageDTO
     */
    contenu?: string;
    /**
     * 
     * @type {string}
     * @memberof RetourMessageDTO
     */
    tempsEnvoi?: string;
}

/**
 * Check if a given object implements the RetourMessageDTO interface.
 */
export function instanceOfRetourMessageDTO(value: object): value is RetourMessageDTO {
    return true;
}

export function RetourMessageDTOFromJSON(json: any): RetourMessageDTO {
    return RetourMessageDTOFromJSONTyped(json, false);
}

export function RetourMessageDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): RetourMessageDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'envoyeurId': json['envoyeurId'] == null ? undefined : json['envoyeurId'],
        'contenu': json['contenu'] == null ? undefined : json['contenu'],
        'tempsEnvoi': json['tempsEnvoi'] == null ? undefined : json['tempsEnvoi'],
    };
}

export function RetourMessageDTOToJSON(json: any): RetourMessageDTO {
    return RetourMessageDTOToJSONTyped(json, false);
}

export function RetourMessageDTOToJSONTyped(value?: RetourMessageDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'envoyeurId': value['envoyeurId'],
        'contenu': value['contenu'],
        'tempsEnvoi': value['tempsEnvoi'],
    };
}

