/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RetourEtudiantDTO } from './RetourEtudiantDTO';
import {
    RetourEtudiantDTOFromJSON,
    RetourEtudiantDTOFromJSONTyped,
    RetourEtudiantDTOToJSON,
    RetourEtudiantDTOToJSONTyped,
} from './RetourEtudiantDTO';

/**
 * 
 * @export
 * @interface RetourAuthentificationDTO
 */
export interface RetourAuthentificationDTO {
    /**
     * 
     * @type {RetourEtudiantDTO}
     * @memberof RetourAuthentificationDTO
     */
    etudiant?: RetourEtudiantDTO;
    /**
     * 
     * @type {string}
     * @memberof RetourAuthentificationDTO
     */
    token?: string;
}

/**
 * Check if a given object implements the RetourAuthentificationDTO interface.
 */
export function instanceOfRetourAuthentificationDTO(value: object): value is RetourAuthentificationDTO {
    return true;
}

export function RetourAuthentificationDTOFromJSON(json: any): RetourAuthentificationDTO {
    return RetourAuthentificationDTOFromJSONTyped(json, false);
}

export function RetourAuthentificationDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): RetourAuthentificationDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'etudiant': json['etudiant'] == null ? undefined : RetourEtudiantDTOFromJSON(json['etudiant']),
        'token': json['token'] == null ? undefined : json['token'],
    };
}

export function RetourAuthentificationDTOToJSON(json: any): RetourAuthentificationDTO {
    return RetourAuthentificationDTOToJSONTyped(json, false);
}

export function RetourAuthentificationDTOToJSONTyped(value?: RetourAuthentificationDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'etudiant': RetourEtudiantDTOToJSON(value['etudiant']),
        'token': value['token'],
    };
}

