/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SupprimerGroupeDTO
 */
export interface SupprimerGroupeDTO {
    /**
     * 
     * @type {string}
     * @memberof SupprimerGroupeDTO
     */
    groupeId?: string;
    /**
     * 
     * @type {string}
     * @memberof SupprimerGroupeDTO
     */
    chefId?: string;
}

/**
 * Check if a given object implements the SupprimerGroupeDTO interface.
 */
export function instanceOfSupprimerGroupeDTO(value: object): value is SupprimerGroupeDTO {
    return true;
}

export function SupprimerGroupeDTOFromJSON(json: any): SupprimerGroupeDTO {
    return SupprimerGroupeDTOFromJSONTyped(json, false);
}

export function SupprimerGroupeDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): SupprimerGroupeDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'groupeId': json['groupeId'] == null ? undefined : json['groupeId'],
        'chefId': json['chefId'] == null ? undefined : json['chefId'],
    };
}

export function SupprimerGroupeDTOToJSON(json: any): SupprimerGroupeDTO {
    return SupprimerGroupeDTOToJSONTyped(json, false);
}

export function SupprimerGroupeDTOToJSONTyped(value?: SupprimerGroupeDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'groupeId': value['groupeId'],
        'chefId': value['chefId'],
    };
}

