/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AjouterActiviteDTOEtudiant,
  AuthentificationDTO,
  CreationConversationDTO,
  CreationDeGroupeDTO,
  CreationEtudiantDTO,
  Etudiant,
  Groupe,
  Horaire,
  INVITATIONGROUPEDTO,
  MiseAJourEtudiantMotDePasse,
  MiseAJourEtudiantProfil,
  Notification,
  QuitterGroupeDTO,
  RequeteActiviteGroupeDTO,
  RequeteInvitationDTO,
  SucessDTO,
  SupprimerEtudiantDTO,
  SupprimerGroupeDTO,
  VirerEtudiantDTO,
} from '../models/index';
import {
    AjouterActiviteDTOEtudiantFromJSON,
    AjouterActiviteDTOEtudiantToJSON,
    AuthentificationDTOFromJSON,
    AuthentificationDTOToJSON,
    CreationConversationDTOFromJSON,
    CreationConversationDTOToJSON,
    CreationDeGroupeDTOFromJSON,
    CreationDeGroupeDTOToJSON,
    CreationEtudiantDTOFromJSON,
    CreationEtudiantDTOToJSON,
    EtudiantFromJSON,
    EtudiantToJSON,
    GroupeFromJSON,
    GroupeToJSON,
    HoraireFromJSON,
    HoraireToJSON,
    INVITATIONGROUPEDTOFromJSON,
    INVITATIONGROUPEDTOToJSON,
    MiseAJourEtudiantMotDePasseFromJSON,
    MiseAJourEtudiantMotDePasseToJSON,
    MiseAJourEtudiantProfilFromJSON,
    MiseAJourEtudiantProfilToJSON,
    NotificationFromJSON,
    NotificationToJSON,
    QuitterGroupeDTOFromJSON,
    QuitterGroupeDTOToJSON,
    RequeteActiviteGroupeDTOFromJSON,
    RequeteActiviteGroupeDTOToJSON,
    RequeteInvitationDTOFromJSON,
    RequeteInvitationDTOToJSON,
    SucessDTOFromJSON,
    SucessDTOToJSON,
    SupprimerEtudiantDTOFromJSON,
    SupprimerEtudiantDTOToJSON,
    SupprimerGroupeDTOFromJSON,
    SupprimerGroupeDTOToJSON,
    VirerEtudiantDTOFromJSON,
    VirerEtudiantDTOToJSON,
} from '../models/index';

export interface AjouterActiviteRequest {
    requeteActiviteGroupeDTO: RequeteActiviteGroupeDTO;
}

export interface AjouterActivitePourEtudiantRequest {
    ajouterActiviteDTOEtudiant: AjouterActiviteDTOEtudiant;
}

export interface AjouterEtudiantDansGroupeRequest {
    iNVITATIONGROUPEDTO: INVITATIONGROUPEDTO;
}

export interface CreateEtudiantRequest {
    creationEtudiantDTO: CreationEtudiantDTO;
}

export interface CreateGroupRequest {
    creationDeGroupeDTO: CreationDeGroupeDTO;
}

export interface CreerConversationRequest {
    id: string;
    creationConversationDTO: CreationConversationDTO;
}

export interface DeleteEtudiantRequest {
    supprimerEtudiantDTO: SupprimerEtudiantDTO;
}

export interface DeleteNotificationRequest {
    idNotification: string;
}

export interface EnvoyerInvitationGroupeRequest {
    requeteInvitationDTO: RequeteInvitationDTO;
}

export interface GetAllNotificationsFromEtudiantRequest {
    idEtudiant: string;
}

export interface GetEtudiantByAuthRequest {
    authentificationDTO: AuthentificationDTO;
}

export interface GetEtudiantByIdRequest {
    id: string;
}

export interface GetEtudiantByUsernameRequest {
    username: string;
}

export interface GetGroupByIdRequest {
    idGroupe: string;
}

export interface GetGroupsFromEtudiantRequest {
    idEtudiant: string;
}

export interface GetHoraireByIdRequest {
    id: string;
}

export interface QuitterGroupeRequest {
    quitterGroupeDTO: QuitterGroupeDTO;
}

export interface RetirerActiviteRequest {
    activiteId: string;
}

export interface RetirerGroupeRequest {
    supprimerGroupeDTO: SupprimerGroupeDTO;
}

export interface SetNotificationToWasSeenRequest {
    idNotification: string;
}

export interface UpdateEtudiantPasswordRequest {
    miseAJourEtudiantMotDePasse: MiseAJourEtudiantMotDePasse;
}

export interface UpdateEtudiantProfileRequest {
    miseAJourEtudiantProfil: MiseAJourEtudiantProfil;
}

export interface VirerEtudiantDunGroupeRequest {
    virerEtudiantDTO: VirerEtudiantDTO;
}

/**
 * TestControlleurApi - interface
 * 
 * @export
 * @interface TestControlleurApiInterface
 */
export interface TestControlleurApiInterface {
    /**
     * Creates request options for ajouterActivite without sending the request
     * @param {RequeteActiviteGroupeDTO} requeteActiviteGroupeDTO 
     * @throws {RequiredError}
     * @memberof TestControlleurApiInterface
     */
    ajouterActiviteRequestOpts(requestParameters: AjouterActiviteRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @param {RequeteActiviteGroupeDTO} requeteActiviteGroupeDTO 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TestControlleurApiInterface
     */
    ajouterActiviteRaw(requestParameters: AjouterActiviteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SucessDTO>>;

    /**
     */
    ajouterActivite(requestParameters: AjouterActiviteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SucessDTO>;

    /**
     * Creates request options for ajouterActivitePourEtudiant without sending the request
     * @param {AjouterActiviteDTOEtudiant} ajouterActiviteDTOEtudiant 
     * @throws {RequiredError}
     * @memberof TestControlleurApiInterface
     */
    ajouterActivitePourEtudiantRequestOpts(requestParameters: AjouterActivitePourEtudiantRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @param {AjouterActiviteDTOEtudiant} ajouterActiviteDTOEtudiant 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TestControlleurApiInterface
     */
    ajouterActivitePourEtudiantRaw(requestParameters: AjouterActivitePourEtudiantRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SucessDTO>>;

    /**
     */
    ajouterActivitePourEtudiant(requestParameters: AjouterActivitePourEtudiantRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SucessDTO>;

    /**
     * Creates request options for ajouterEtudiantDansGroupe without sending the request
     * @param {INVITATIONGROUPEDTO} iNVITATIONGROUPEDTO 
     * @throws {RequiredError}
     * @memberof TestControlleurApiInterface
     */
    ajouterEtudiantDansGroupeRequestOpts(requestParameters: AjouterEtudiantDansGroupeRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @param {INVITATIONGROUPEDTO} iNVITATIONGROUPEDTO 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TestControlleurApiInterface
     */
    ajouterEtudiantDansGroupeRaw(requestParameters: AjouterEtudiantDansGroupeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SucessDTO>>;

    /**
     */
    ajouterEtudiantDansGroupe(requestParameters: AjouterEtudiantDansGroupeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SucessDTO>;

    /**
     * Creates request options for createEtudiant without sending the request
     * @param {CreationEtudiantDTO} creationEtudiantDTO 
     * @throws {RequiredError}
     * @memberof TestControlleurApiInterface
     */
    createEtudiantRequestOpts(requestParameters: CreateEtudiantRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @param {CreationEtudiantDTO} creationEtudiantDTO 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TestControlleurApiInterface
     */
    createEtudiantRaw(requestParameters: CreateEtudiantRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Etudiant>>;

    /**
     */
    createEtudiant(requestParameters: CreateEtudiantRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Etudiant>;

    /**
     * Creates request options for createGroup without sending the request
     * @param {CreationDeGroupeDTO} creationDeGroupeDTO 
     * @throws {RequiredError}
     * @memberof TestControlleurApiInterface
     */
    createGroupRequestOpts(requestParameters: CreateGroupRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @param {CreationDeGroupeDTO} creationDeGroupeDTO 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TestControlleurApiInterface
     */
    createGroupRaw(requestParameters: CreateGroupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Groupe>>;

    /**
     */
    createGroup(requestParameters: CreateGroupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Groupe>;

    /**
     * Creates request options for creerConversation without sending the request
     * @param {string} id 
     * @param {CreationConversationDTO} creationConversationDTO 
     * @throws {RequiredError}
     * @memberof TestControlleurApiInterface
     */
    creerConversationRequestOpts(requestParameters: CreerConversationRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @param {string} id 
     * @param {CreationConversationDTO} creationConversationDTO 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TestControlleurApiInterface
     */
    creerConversationRaw(requestParameters: CreerConversationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SucessDTO>>;

    /**
     */
    creerConversation(requestParameters: CreerConversationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SucessDTO>;

    /**
     * Creates request options for deleteEtudiant without sending the request
     * @param {SupprimerEtudiantDTO} supprimerEtudiantDTO 
     * @throws {RequiredError}
     * @memberof TestControlleurApiInterface
     */
    deleteEtudiantRequestOpts(requestParameters: DeleteEtudiantRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @param {SupprimerEtudiantDTO} supprimerEtudiantDTO 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TestControlleurApiInterface
     */
    deleteEtudiantRaw(requestParameters: DeleteEtudiantRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SucessDTO>>;

    /**
     */
    deleteEtudiant(requestParameters: DeleteEtudiantRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SucessDTO>;

    /**
     * Creates request options for deleteNotification without sending the request
     * @param {string} idNotification 
     * @throws {RequiredError}
     * @memberof TestControlleurApiInterface
     */
    deleteNotificationRequestOpts(requestParameters: DeleteNotificationRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @param {string} idNotification 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TestControlleurApiInterface
     */
    deleteNotificationRaw(requestParameters: DeleteNotificationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SucessDTO>>;

    /**
     */
    deleteNotification(requestParameters: DeleteNotificationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SucessDTO>;

    /**
     * Creates request options for envoyerInvitationGroupe without sending the request
     * @param {RequeteInvitationDTO} requeteInvitationDTO 
     * @throws {RequiredError}
     * @memberof TestControlleurApiInterface
     */
    envoyerInvitationGroupeRequestOpts(requestParameters: EnvoyerInvitationGroupeRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @param {RequeteInvitationDTO} requeteInvitationDTO 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TestControlleurApiInterface
     */
    envoyerInvitationGroupeRaw(requestParameters: EnvoyerInvitationGroupeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SucessDTO>>;

    /**
     */
    envoyerInvitationGroupe(requestParameters: EnvoyerInvitationGroupeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SucessDTO>;

    /**
     * Creates request options for getAllNotificationsFromEtudiant without sending the request
     * @param {string} idEtudiant 
     * @throws {RequiredError}
     * @memberof TestControlleurApiInterface
     */
    getAllNotificationsFromEtudiantRequestOpts(requestParameters: GetAllNotificationsFromEtudiantRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @param {string} idEtudiant 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TestControlleurApiInterface
     */
    getAllNotificationsFromEtudiantRaw(requestParameters: GetAllNotificationsFromEtudiantRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Notification>>>;

    /**
     */
    getAllNotificationsFromEtudiant(requestParameters: GetAllNotificationsFromEtudiantRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Notification>>;

    /**
     * Creates request options for getEtudiantByAuth without sending the request
     * @param {AuthentificationDTO} authentificationDTO 
     * @throws {RequiredError}
     * @memberof TestControlleurApiInterface
     */
    getEtudiantByAuthRequestOpts(requestParameters: GetEtudiantByAuthRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @param {AuthentificationDTO} authentificationDTO 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TestControlleurApiInterface
     */
    getEtudiantByAuthRaw(requestParameters: GetEtudiantByAuthRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Etudiant>>;

    /**
     */
    getEtudiantByAuth(requestParameters: GetEtudiantByAuthRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Etudiant>;

    /**
     * Creates request options for getEtudiantById without sending the request
     * @param {string} id 
     * @throws {RequiredError}
     * @memberof TestControlleurApiInterface
     */
    getEtudiantByIdRequestOpts(requestParameters: GetEtudiantByIdRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TestControlleurApiInterface
     */
    getEtudiantByIdRaw(requestParameters: GetEtudiantByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Etudiant>>;

    /**
     */
    getEtudiantById(requestParameters: GetEtudiantByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Etudiant>;

    /**
     * Creates request options for getEtudiantByUsername without sending the request
     * @param {string} username 
     * @throws {RequiredError}
     * @memberof TestControlleurApiInterface
     */
    getEtudiantByUsernameRequestOpts(requestParameters: GetEtudiantByUsernameRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @param {string} username 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TestControlleurApiInterface
     */
    getEtudiantByUsernameRaw(requestParameters: GetEtudiantByUsernameRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Etudiant>>;

    /**
     */
    getEtudiantByUsername(requestParameters: GetEtudiantByUsernameRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Etudiant>;

    /**
     * Creates request options for getGroupById without sending the request
     * @param {string} idGroupe 
     * @throws {RequiredError}
     * @memberof TestControlleurApiInterface
     */
    getGroupByIdRequestOpts(requestParameters: GetGroupByIdRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @param {string} idGroupe 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TestControlleurApiInterface
     */
    getGroupByIdRaw(requestParameters: GetGroupByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Groupe>>;

    /**
     */
    getGroupById(requestParameters: GetGroupByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Groupe>;

    /**
     * Creates request options for getGroupsFromEtudiant without sending the request
     * @param {string} idEtudiant 
     * @throws {RequiredError}
     * @memberof TestControlleurApiInterface
     */
    getGroupsFromEtudiantRequestOpts(requestParameters: GetGroupsFromEtudiantRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @param {string} idEtudiant 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TestControlleurApiInterface
     */
    getGroupsFromEtudiantRaw(requestParameters: GetGroupsFromEtudiantRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Groupe>>>;

    /**
     */
    getGroupsFromEtudiant(requestParameters: GetGroupsFromEtudiantRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Groupe>>;

    /**
     * Creates request options for getHoraireById without sending the request
     * @param {string} id 
     * @throws {RequiredError}
     * @memberof TestControlleurApiInterface
     */
    getHoraireByIdRequestOpts(requestParameters: GetHoraireByIdRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TestControlleurApiInterface
     */
    getHoraireByIdRaw(requestParameters: GetHoraireByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Horaire>>;

    /**
     */
    getHoraireById(requestParameters: GetHoraireByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Horaire>;

    /**
     * Creates request options for quitterGroupe without sending the request
     * @param {QuitterGroupeDTO} quitterGroupeDTO 
     * @throws {RequiredError}
     * @memberof TestControlleurApiInterface
     */
    quitterGroupeRequestOpts(requestParameters: QuitterGroupeRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @param {QuitterGroupeDTO} quitterGroupeDTO 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TestControlleurApiInterface
     */
    quitterGroupeRaw(requestParameters: QuitterGroupeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SucessDTO>>;

    /**
     */
    quitterGroupe(requestParameters: QuitterGroupeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SucessDTO>;

    /**
     * Creates request options for retirerActivite without sending the request
     * @param {string} activiteId 
     * @throws {RequiredError}
     * @memberof TestControlleurApiInterface
     */
    retirerActiviteRequestOpts(requestParameters: RetirerActiviteRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @param {string} activiteId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TestControlleurApiInterface
     */
    retirerActiviteRaw(requestParameters: RetirerActiviteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SucessDTO>>;

    /**
     */
    retirerActivite(requestParameters: RetirerActiviteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SucessDTO>;

    /**
     * Creates request options for retirerGroupe without sending the request
     * @param {SupprimerGroupeDTO} supprimerGroupeDTO 
     * @throws {RequiredError}
     * @memberof TestControlleurApiInterface
     */
    retirerGroupeRequestOpts(requestParameters: RetirerGroupeRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @param {SupprimerGroupeDTO} supprimerGroupeDTO 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TestControlleurApiInterface
     */
    retirerGroupeRaw(requestParameters: RetirerGroupeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SucessDTO>>;

    /**
     */
    retirerGroupe(requestParameters: RetirerGroupeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SucessDTO>;

    /**
     * Creates request options for setNotificationToWasSeen without sending the request
     * @param {string} idNotification 
     * @throws {RequiredError}
     * @memberof TestControlleurApiInterface
     */
    setNotificationToWasSeenRequestOpts(requestParameters: SetNotificationToWasSeenRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @param {string} idNotification 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TestControlleurApiInterface
     */
    setNotificationToWasSeenRaw(requestParameters: SetNotificationToWasSeenRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SucessDTO>>;

    /**
     */
    setNotificationToWasSeen(requestParameters: SetNotificationToWasSeenRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SucessDTO>;

    /**
     * Creates request options for updateEtudiantPassword without sending the request
     * @param {MiseAJourEtudiantMotDePasse} miseAJourEtudiantMotDePasse 
     * @throws {RequiredError}
     * @memberof TestControlleurApiInterface
     */
    updateEtudiantPasswordRequestOpts(requestParameters: UpdateEtudiantPasswordRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @param {MiseAJourEtudiantMotDePasse} miseAJourEtudiantMotDePasse 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TestControlleurApiInterface
     */
    updateEtudiantPasswordRaw(requestParameters: UpdateEtudiantPasswordRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SucessDTO>>;

    /**
     */
    updateEtudiantPassword(requestParameters: UpdateEtudiantPasswordRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SucessDTO>;

    /**
     * Creates request options for updateEtudiantProfile without sending the request
     * @param {MiseAJourEtudiantProfil} miseAJourEtudiantProfil 
     * @throws {RequiredError}
     * @memberof TestControlleurApiInterface
     */
    updateEtudiantProfileRequestOpts(requestParameters: UpdateEtudiantProfileRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @param {MiseAJourEtudiantProfil} miseAJourEtudiantProfil 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TestControlleurApiInterface
     */
    updateEtudiantProfileRaw(requestParameters: UpdateEtudiantProfileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SucessDTO>>;

    /**
     */
    updateEtudiantProfile(requestParameters: UpdateEtudiantProfileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SucessDTO>;

    /**
     * Creates request options for virerEtudiantDunGroupe without sending the request
     * @param {VirerEtudiantDTO} virerEtudiantDTO 
     * @throws {RequiredError}
     * @memberof TestControlleurApiInterface
     */
    virerEtudiantDunGroupeRequestOpts(requestParameters: VirerEtudiantDunGroupeRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @param {VirerEtudiantDTO} virerEtudiantDTO 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TestControlleurApiInterface
     */
    virerEtudiantDunGroupeRaw(requestParameters: VirerEtudiantDunGroupeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SucessDTO>>;

    /**
     */
    virerEtudiantDunGroupe(requestParameters: VirerEtudiantDunGroupeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SucessDTO>;

}

/**
 * 
 */
export class TestControlleurApi extends runtime.BaseAPI implements TestControlleurApiInterface {

    /**
     * Creates request options for ajouterActivite without sending the request
     */
    async ajouterActiviteRequestOpts(requestParameters: AjouterActiviteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['requeteActiviteGroupeDTO'] == null) {
            throw new runtime.RequiredError(
                'requeteActiviteGroupeDTO',
                'Required parameter "requeteActiviteGroupeDTO" was null or undefined when calling ajouterActivite().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/groupes/activites/ajouter`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RequeteActiviteGroupeDTOToJSON(requestParameters['requeteActiviteGroupeDTO']),
        };
    }

    /**
     */
    async ajouterActiviteRaw(requestParameters: AjouterActiviteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SucessDTO>> {
        const requestOptions = await this.ajouterActiviteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SucessDTOFromJSON(jsonValue));
    }

    /**
     */
    async ajouterActivite(requestParameters: AjouterActiviteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SucessDTO> {
        const response = await this.ajouterActiviteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for ajouterActivitePourEtudiant without sending the request
     */
    async ajouterActivitePourEtudiantRequestOpts(requestParameters: AjouterActivitePourEtudiantRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['ajouterActiviteDTOEtudiant'] == null) {
            throw new runtime.RequiredError(
                'ajouterActiviteDTOEtudiant',
                'Required parameter "ajouterActiviteDTOEtudiant" was null or undefined when calling ajouterActivitePourEtudiant().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/etudiants/activites/ajouter`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AjouterActiviteDTOEtudiantToJSON(requestParameters['ajouterActiviteDTOEtudiant']),
        };
    }

    /**
     */
    async ajouterActivitePourEtudiantRaw(requestParameters: AjouterActivitePourEtudiantRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SucessDTO>> {
        const requestOptions = await this.ajouterActivitePourEtudiantRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SucessDTOFromJSON(jsonValue));
    }

    /**
     */
    async ajouterActivitePourEtudiant(requestParameters: AjouterActivitePourEtudiantRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SucessDTO> {
        const response = await this.ajouterActivitePourEtudiantRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for ajouterEtudiantDansGroupe without sending the request
     */
    async ajouterEtudiantDansGroupeRequestOpts(requestParameters: AjouterEtudiantDansGroupeRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['iNVITATIONGROUPEDTO'] == null) {
            throw new runtime.RequiredError(
                'iNVITATIONGROUPEDTO',
                'Required parameter "iNVITATIONGROUPEDTO" was null or undefined when calling ajouterEtudiantDansGroupe().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/groupes/ajouter`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: INVITATIONGROUPEDTOToJSON(requestParameters['iNVITATIONGROUPEDTO']),
        };
    }

    /**
     */
    async ajouterEtudiantDansGroupeRaw(requestParameters: AjouterEtudiantDansGroupeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SucessDTO>> {
        const requestOptions = await this.ajouterEtudiantDansGroupeRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SucessDTOFromJSON(jsonValue));
    }

    /**
     */
    async ajouterEtudiantDansGroupe(requestParameters: AjouterEtudiantDansGroupeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SucessDTO> {
        const response = await this.ajouterEtudiantDansGroupeRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createEtudiant without sending the request
     */
    async createEtudiantRequestOpts(requestParameters: CreateEtudiantRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['creationEtudiantDTO'] == null) {
            throw new runtime.RequiredError(
                'creationEtudiantDTO',
                'Required parameter "creationEtudiantDTO" was null or undefined when calling createEtudiant().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/etudiants`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreationEtudiantDTOToJSON(requestParameters['creationEtudiantDTO']),
        };
    }

    /**
     */
    async createEtudiantRaw(requestParameters: CreateEtudiantRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Etudiant>> {
        const requestOptions = await this.createEtudiantRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EtudiantFromJSON(jsonValue));
    }

    /**
     */
    async createEtudiant(requestParameters: CreateEtudiantRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Etudiant> {
        const response = await this.createEtudiantRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createGroup without sending the request
     */
    async createGroupRequestOpts(requestParameters: CreateGroupRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['creationDeGroupeDTO'] == null) {
            throw new runtime.RequiredError(
                'creationDeGroupeDTO',
                'Required parameter "creationDeGroupeDTO" was null or undefined when calling createGroup().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/groupes`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreationDeGroupeDTOToJSON(requestParameters['creationDeGroupeDTO']),
        };
    }

    /**
     */
    async createGroupRaw(requestParameters: CreateGroupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Groupe>> {
        const requestOptions = await this.createGroupRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GroupeFromJSON(jsonValue));
    }

    /**
     */
    async createGroup(requestParameters: CreateGroupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Groupe> {
        const response = await this.createGroupRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for creerConversation without sending the request
     */
    async creerConversationRequestOpts(requestParameters: CreerConversationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling creerConversation().'
            );
        }

        if (requestParameters['creationConversationDTO'] == null) {
            throw new runtime.RequiredError(
                'creationConversationDTO',
                'Required parameter "creationConversationDTO" was null or undefined when calling creerConversation().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['id'] != null) {
            queryParameters['id'] = requestParameters['id'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/conversations`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreationConversationDTOToJSON(requestParameters['creationConversationDTO']),
        };
    }

    /**
     */
    async creerConversationRaw(requestParameters: CreerConversationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SucessDTO>> {
        const requestOptions = await this.creerConversationRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SucessDTOFromJSON(jsonValue));
    }

    /**
     */
    async creerConversation(requestParameters: CreerConversationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SucessDTO> {
        const response = await this.creerConversationRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteEtudiant without sending the request
     */
    async deleteEtudiantRequestOpts(requestParameters: DeleteEtudiantRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['supprimerEtudiantDTO'] == null) {
            throw new runtime.RequiredError(
                'supprimerEtudiantDTO',
                'Required parameter "supprimerEtudiantDTO" was null or undefined when calling deleteEtudiant().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/etudiants`;

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
            body: SupprimerEtudiantDTOToJSON(requestParameters['supprimerEtudiantDTO']),
        };
    }

    /**
     */
    async deleteEtudiantRaw(requestParameters: DeleteEtudiantRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SucessDTO>> {
        const requestOptions = await this.deleteEtudiantRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SucessDTOFromJSON(jsonValue));
    }

    /**
     */
    async deleteEtudiant(requestParameters: DeleteEtudiantRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SucessDTO> {
        const response = await this.deleteEtudiantRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteNotification without sending the request
     */
    async deleteNotificationRequestOpts(requestParameters: DeleteNotificationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['idNotification'] == null) {
            throw new runtime.RequiredError(
                'idNotification',
                'Required parameter "idNotification" was null or undefined when calling deleteNotification().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['idNotification'] != null) {
            queryParameters['idNotification'] = requestParameters['idNotification'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/notifications`;

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async deleteNotificationRaw(requestParameters: DeleteNotificationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SucessDTO>> {
        const requestOptions = await this.deleteNotificationRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SucessDTOFromJSON(jsonValue));
    }

    /**
     */
    async deleteNotification(requestParameters: DeleteNotificationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SucessDTO> {
        const response = await this.deleteNotificationRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for envoyerInvitationGroupe without sending the request
     */
    async envoyerInvitationGroupeRequestOpts(requestParameters: EnvoyerInvitationGroupeRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['requeteInvitationDTO'] == null) {
            throw new runtime.RequiredError(
                'requeteInvitationDTO',
                'Required parameter "requeteInvitationDTO" was null or undefined when calling envoyerInvitationGroupe().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/groupes/invitations`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RequeteInvitationDTOToJSON(requestParameters['requeteInvitationDTO']),
        };
    }

    /**
     */
    async envoyerInvitationGroupeRaw(requestParameters: EnvoyerInvitationGroupeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SucessDTO>> {
        const requestOptions = await this.envoyerInvitationGroupeRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SucessDTOFromJSON(jsonValue));
    }

    /**
     */
    async envoyerInvitationGroupe(requestParameters: EnvoyerInvitationGroupeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SucessDTO> {
        const response = await this.envoyerInvitationGroupeRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getAllNotificationsFromEtudiant without sending the request
     */
    async getAllNotificationsFromEtudiantRequestOpts(requestParameters: GetAllNotificationsFromEtudiantRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['idEtudiant'] == null) {
            throw new runtime.RequiredError(
                'idEtudiant',
                'Required parameter "idEtudiant" was null or undefined when calling getAllNotificationsFromEtudiant().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['idEtudiant'] != null) {
            queryParameters['idEtudiant'] = requestParameters['idEtudiant'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/notifications`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async getAllNotificationsFromEtudiantRaw(requestParameters: GetAllNotificationsFromEtudiantRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Notification>>> {
        const requestOptions = await this.getAllNotificationsFromEtudiantRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(NotificationFromJSON));
    }

    /**
     */
    async getAllNotificationsFromEtudiant(requestParameters: GetAllNotificationsFromEtudiantRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Notification>> {
        const response = await this.getAllNotificationsFromEtudiantRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getEtudiantByAuth without sending the request
     */
    async getEtudiantByAuthRequestOpts(requestParameters: GetEtudiantByAuthRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['authentificationDTO'] == null) {
            throw new runtime.RequiredError(
                'authentificationDTO',
                'Required parameter "authentificationDTO" was null or undefined when calling getEtudiantByAuth().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/etudiant/auth`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AuthentificationDTOToJSON(requestParameters['authentificationDTO']),
        };
    }

    /**
     */
    async getEtudiantByAuthRaw(requestParameters: GetEtudiantByAuthRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Etudiant>> {
        const requestOptions = await this.getEtudiantByAuthRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EtudiantFromJSON(jsonValue));
    }

    /**
     */
    async getEtudiantByAuth(requestParameters: GetEtudiantByAuthRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Etudiant> {
        const response = await this.getEtudiantByAuthRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getEtudiantById without sending the request
     */
    async getEtudiantByIdRequestOpts(requestParameters: GetEtudiantByIdRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getEtudiantById().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['id'] != null) {
            queryParameters['id'] = requestParameters['id'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/etudiant`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async getEtudiantByIdRaw(requestParameters: GetEtudiantByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Etudiant>> {
        const requestOptions = await this.getEtudiantByIdRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EtudiantFromJSON(jsonValue));
    }

    /**
     */
    async getEtudiantById(requestParameters: GetEtudiantByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Etudiant> {
        const response = await this.getEtudiantByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getEtudiantByUsername without sending the request
     */
    async getEtudiantByUsernameRequestOpts(requestParameters: GetEtudiantByUsernameRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['username'] == null) {
            throw new runtime.RequiredError(
                'username',
                'Required parameter "username" was null or undefined when calling getEtudiantByUsername().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['username'] != null) {
            queryParameters['username'] = requestParameters['username'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/etudiant/username`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async getEtudiantByUsernameRaw(requestParameters: GetEtudiantByUsernameRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Etudiant>> {
        const requestOptions = await this.getEtudiantByUsernameRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EtudiantFromJSON(jsonValue));
    }

    /**
     */
    async getEtudiantByUsername(requestParameters: GetEtudiantByUsernameRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Etudiant> {
        const response = await this.getEtudiantByUsernameRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getGroupById without sending the request
     */
    async getGroupByIdRequestOpts(requestParameters: GetGroupByIdRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['idGroupe'] == null) {
            throw new runtime.RequiredError(
                'idGroupe',
                'Required parameter "idGroupe" was null or undefined when calling getGroupById().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['idGroupe'] != null) {
            queryParameters['idGroupe'] = requestParameters['idGroupe'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/groupe`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async getGroupByIdRaw(requestParameters: GetGroupByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Groupe>> {
        const requestOptions = await this.getGroupByIdRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GroupeFromJSON(jsonValue));
    }

    /**
     */
    async getGroupById(requestParameters: GetGroupByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Groupe> {
        const response = await this.getGroupByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getGroupsFromEtudiant without sending the request
     */
    async getGroupsFromEtudiantRequestOpts(requestParameters: GetGroupsFromEtudiantRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['idEtudiant'] == null) {
            throw new runtime.RequiredError(
                'idEtudiant',
                'Required parameter "idEtudiant" was null or undefined when calling getGroupsFromEtudiant().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['idEtudiant'] != null) {
            queryParameters['idEtudiant'] = requestParameters['idEtudiant'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/groupes`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async getGroupsFromEtudiantRaw(requestParameters: GetGroupsFromEtudiantRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Groupe>>> {
        const requestOptions = await this.getGroupsFromEtudiantRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(GroupeFromJSON));
    }

    /**
     */
    async getGroupsFromEtudiant(requestParameters: GetGroupsFromEtudiantRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Groupe>> {
        const response = await this.getGroupsFromEtudiantRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getHoraireById without sending the request
     */
    async getHoraireByIdRequestOpts(requestParameters: GetHoraireByIdRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getHoraireById().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['id'] != null) {
            queryParameters['id'] = requestParameters['id'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/horaire`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async getHoraireByIdRaw(requestParameters: GetHoraireByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Horaire>> {
        const requestOptions = await this.getHoraireByIdRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => HoraireFromJSON(jsonValue));
    }

    /**
     */
    async getHoraireById(requestParameters: GetHoraireByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Horaire> {
        const response = await this.getHoraireByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for quitterGroupe without sending the request
     */
    async quitterGroupeRequestOpts(requestParameters: QuitterGroupeRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['quitterGroupeDTO'] == null) {
            throw new runtime.RequiredError(
                'quitterGroupeDTO',
                'Required parameter "quitterGroupeDTO" was null or undefined when calling quitterGroupe().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/groupes/quitter`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: QuitterGroupeDTOToJSON(requestParameters['quitterGroupeDTO']),
        };
    }

    /**
     */
    async quitterGroupeRaw(requestParameters: QuitterGroupeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SucessDTO>> {
        const requestOptions = await this.quitterGroupeRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SucessDTOFromJSON(jsonValue));
    }

    /**
     */
    async quitterGroupe(requestParameters: QuitterGroupeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SucessDTO> {
        const response = await this.quitterGroupeRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for retirerActivite without sending the request
     */
    async retirerActiviteRequestOpts(requestParameters: RetirerActiviteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['activiteId'] == null) {
            throw new runtime.RequiredError(
                'activiteId',
                'Required parameter "activiteId" was null or undefined when calling retirerActivite().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['activiteId'] != null) {
            queryParameters['activiteId'] = requestParameters['activiteId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/activite/retirer`;

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async retirerActiviteRaw(requestParameters: RetirerActiviteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SucessDTO>> {
        const requestOptions = await this.retirerActiviteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SucessDTOFromJSON(jsonValue));
    }

    /**
     */
    async retirerActivite(requestParameters: RetirerActiviteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SucessDTO> {
        const response = await this.retirerActiviteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for retirerGroupe without sending the request
     */
    async retirerGroupeRequestOpts(requestParameters: RetirerGroupeRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['supprimerGroupeDTO'] == null) {
            throw new runtime.RequiredError(
                'supprimerGroupeDTO',
                'Required parameter "supprimerGroupeDTO" was null or undefined when calling retirerGroupe().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/groupe/supprimer`;

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
            body: SupprimerGroupeDTOToJSON(requestParameters['supprimerGroupeDTO']),
        };
    }

    /**
     */
    async retirerGroupeRaw(requestParameters: RetirerGroupeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SucessDTO>> {
        const requestOptions = await this.retirerGroupeRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SucessDTOFromJSON(jsonValue));
    }

    /**
     */
    async retirerGroupe(requestParameters: RetirerGroupeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SucessDTO> {
        const response = await this.retirerGroupeRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for setNotificationToWasSeen without sending the request
     */
    async setNotificationToWasSeenRequestOpts(requestParameters: SetNotificationToWasSeenRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['idNotification'] == null) {
            throw new runtime.RequiredError(
                'idNotification',
                'Required parameter "idNotification" was null or undefined when calling setNotificationToWasSeen().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['idNotification'] != null) {
            queryParameters['idNotification'] = requestParameters['idNotification'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/notifications/vue`;

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async setNotificationToWasSeenRaw(requestParameters: SetNotificationToWasSeenRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SucessDTO>> {
        const requestOptions = await this.setNotificationToWasSeenRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SucessDTOFromJSON(jsonValue));
    }

    /**
     */
    async setNotificationToWasSeen(requestParameters: SetNotificationToWasSeenRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SucessDTO> {
        const response = await this.setNotificationToWasSeenRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateEtudiantPassword without sending the request
     */
    async updateEtudiantPasswordRequestOpts(requestParameters: UpdateEtudiantPasswordRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['miseAJourEtudiantMotDePasse'] == null) {
            throw new runtime.RequiredError(
                'miseAJourEtudiantMotDePasse',
                'Required parameter "miseAJourEtudiantMotDePasse" was null or undefined when calling updateEtudiantPassword().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/etudiants/password`;

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: MiseAJourEtudiantMotDePasseToJSON(requestParameters['miseAJourEtudiantMotDePasse']),
        };
    }

    /**
     */
    async updateEtudiantPasswordRaw(requestParameters: UpdateEtudiantPasswordRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SucessDTO>> {
        const requestOptions = await this.updateEtudiantPasswordRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SucessDTOFromJSON(jsonValue));
    }

    /**
     */
    async updateEtudiantPassword(requestParameters: UpdateEtudiantPasswordRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SucessDTO> {
        const response = await this.updateEtudiantPasswordRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateEtudiantProfile without sending the request
     */
    async updateEtudiantProfileRequestOpts(requestParameters: UpdateEtudiantProfileRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['miseAJourEtudiantProfil'] == null) {
            throw new runtime.RequiredError(
                'miseAJourEtudiantProfil',
                'Required parameter "miseAJourEtudiantProfil" was null or undefined when calling updateEtudiantProfile().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/etudiants/profil`;

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: MiseAJourEtudiantProfilToJSON(requestParameters['miseAJourEtudiantProfil']),
        };
    }

    /**
     */
    async updateEtudiantProfileRaw(requestParameters: UpdateEtudiantProfileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SucessDTO>> {
        const requestOptions = await this.updateEtudiantProfileRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SucessDTOFromJSON(jsonValue));
    }

    /**
     */
    async updateEtudiantProfile(requestParameters: UpdateEtudiantProfileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SucessDTO> {
        const response = await this.updateEtudiantProfileRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for virerEtudiantDunGroupe without sending the request
     */
    async virerEtudiantDunGroupeRequestOpts(requestParameters: VirerEtudiantDunGroupeRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['virerEtudiantDTO'] == null) {
            throw new runtime.RequiredError(
                'virerEtudiantDTO',
                'Required parameter "virerEtudiantDTO" was null or undefined when calling virerEtudiantDunGroupe().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/groupes/virer`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: VirerEtudiantDTOToJSON(requestParameters['virerEtudiantDTO']),
        };
    }

    /**
     */
    async virerEtudiantDunGroupeRaw(requestParameters: VirerEtudiantDunGroupeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SucessDTO>> {
        const requestOptions = await this.virerEtudiantDunGroupeRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SucessDTOFromJSON(jsonValue));
    }

    /**
     */
    async virerEtudiantDunGroupe(requestParameters: VirerEtudiantDunGroupeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SucessDTO> {
        const response = await this.virerEtudiantDunGroupeRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
