spring.application.name=LinkUp
spring.datasource.url=jdbc:postgresql://pg-537d8ed-kayrouz-18f5.a.aivencloud.com:23979/defaultdb?sslmode=require
spring.datasource.username=avnadmin
spring.datasource.password=AVNS__bNUXtmSZ5issFOwjcp
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
