
spring.datasource.url=jdbc:postgresql://pg-537d8ed-kayrouz-18f5.a.aivencloud.com:23979/defaultdb
spring.datasource.username=avnadmin
spring.datasource.password=AVNS__bNUXtmSZ5issFOwjcp
spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.connection-timeout=20000

spring.mongodb.uri=mongodb+srv://Saad:adadad@cluster0.jav25ap.mongodb.net/Organisation_projet?retryWrites=true&w=majority

spring.mongodb.connect-timeout=10000
spring.mongodb.socket-timeout=10000

spring.mongodb.min-connections-per-host=0
spring.mongodb.max-connections-per-host=5


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

logging.level.org.mongodb.driver=INFO
logging.level.org.springframework.data.mongodb=DEBUG