spring.datasource.url=jdbc:postgresql://pg-537d8ed-kayrouz-18f5.a.aivencloud.com:23979/defaultdb

spring.datasource.username=avnadmin

spring.datasource.password=AVNS__bNUXtmSZ5issFOwjcp

spring.datasource.driver-class-name=org.postgresql.Driver


spring.mongodb.uri=mongodb+srv://Saad:QLyHyN_9GgnjE4z@cluster0.jav25ap.mongodb.net/linkup?retryWrites=true&w=majority&appName=Cluster0
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.web.servlet.DispatcherServlet=DEBUG