spring.application.name=LinkUp
spring.datasource.url=${AIVEN_JDBC_URL}
spring.datasource.username=${AIVEN_DB_USER}
spring.datasource.password=${AIVEN_DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
server.port=${PORT:8080}