# --- CONFIGURATION POSTGRESQL (Aiven/Render) ---
spring.datasource.url=jdbc:postgresql://pg-537d8ed-kayrouz-18f5.a.aivencloud.com:23979/defaultdb
spring.datasource.username=avnadmin
spring.datasource.password=AVNS__bNUXtmSZ5issFOwjcp
spring.datasource.driver-class-name=org.postgresql.Driver

# --- OPTIMISATION HIKARI (Pour petit serveur) ---
# On limite à 3 connexions max pour économiser la RAM sur Render
spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.connection-timeout=20000

# --- CONFIGURATION MONGODB ATLAS (Spring 4.x) ---
# Note : On utilise le format direct sans le ".data" pour éviter les bugs de scan
spring.mongodb.uri=mongodb+srv://Saad:adadad@cluster0.jav25ap.mongodb.net/Organisation_projet?retryWrites=true&w=majority

# Limites MongoDB pour éviter d'abuser des threads
spring.mongodb.connect-timeout=10000
spring.mongodb.socket-timeout=10000
# On limite aussi le pool de connexions MongoDB (important sur Render !)
spring.mongodb.min-connections-per-host=0
spring.mongodb.max-connections-per-host=5

# --- JPA / HIBERNATE ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# --- LOGS (Pour voir si Atlas se connecte enfin) ---
logging.level.org.mongodb.driver=INFO
logging.level.org.springframework.data.mongodb=DEBUG