spring.application.name=LinkUp
spring.datasource.url=jdbc:postgresql://localhost:5432/linkup
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
